# Generated by Django 4.0.3 on 2022-04-18 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variant',
            old_name='brandId',
            new_name='brand',
        ),
        migrations.AlterField(
            model_name='category',
            name='parentCategoryId',
            field=models.SmallIntegerField(null=True),
        ),
    ]
