# Generated by Django 4.0.3 on 2022-04-18 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_brandid_variant_brand_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variantattribute',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='variantattribute',
            name='variant',
        ),
        migrations.AddField(
            model_name='variant',
            name='attribute',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='product.attribute'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variant',
            name='option',
            field=models.CharField(default='s', max_length=40),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='variant',
            constraint=models.UniqueConstraint(fields=('product', 'attribute', 'option'), name='variant_attribute_unique'),
        ),
        migrations.DeleteModel(
            name='VariantAttribute',
        ),
    ]
