# Generated by Django 4.0.3 on 2022-04-18 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_variantattribute_attribute_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parentCategoryId',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
