# Generated by Django 4.0.3 on 2022-04-18 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_category_parentcategoryid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parentCategoryId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='product.category'),
            preserve_default=False,
        ),
    ]
