# Generated by Django 4.0.3 on 2022-04-18 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_category_parentcategoryid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='id',
            field=models.SmallAutoField(primary_key=True, serialize=False),
        ),
    ]
