# Generated by Django 4.0.3 on 2022-04-18 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_variant_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='brand',
        ),
        migrations.AlterField(
            model_name='variant',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='variant',
            name='shortDescription',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='variant',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
