# Generated by Django 4.0.3 on 2022-11-06 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.UUIDField(default=user.models.get_stateId, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.UUIDField(default=user.models.get_cityId, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=32)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.state')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=user.models.get_addressId, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=10)),
                ('addressType', models.CharField(choices=[('HOME', 'HOME'), ('OFFICE', 'OFFICE'), ('OTHER', 'OTHER')], default='HOME', max_length=10)),
                ('street', models.CharField(max_length=64)),
                ('pincode', models.IntegerField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.city')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
