# Generated by Django 4.0.3 on 2022-04-18 19:34

from django.db import migrations, models
import django.db.models.deletion
import order.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(default=order.models.get_order_id, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('amount', models.FloatField()),
                ('paymentMode', models.CharField(choices=[('CA', 'Cash'), ('CR', 'Credit Card'), ('GP', 'Google Pay')], max_length=2)),
                ('status', models.CharField(choices=[('PLACED', 'PLACED'), ('CONFIRMED', 'CONFIRMED'), ('SHIPPED', 'SHIPPED'), ('OUT FOR DELIVERY', 'OUT FOR DELIVERY'), ('DELIVERED', 'DELIVERED')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.CharField(default=order.models.get_order_item_id, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(choices=[('PLACED', 'PLACED'), ('CONFIRMED', 'CONFIRMED'), ('SHIPPED', 'SHIPPED'), ('OUT FOR DELIVERY', 'OUT FOR DELIVERY'), ('DELIVERED', 'DELIVERED'), ('RETURN PLACED', 'RETURN PLACED'), ('RETURN PROCESSING', 'RETURN PROCESSING'), ('RETURN SUCCESSFUL', 'RETURN SUCCESSFUL')], max_length=20)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.variant')),
            ],
        ),
    ]
