# Generated by Django 4.0.3 on 2022-11-06 12:48

from django.db import migrations, models
import order.models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_address_order_user_alter_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='id',
            field=models.UUIDField(default=order.models.get_order_item_id, primary_key=True, serialize=False, unique=True),
        ),
    ]
